### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/CorporaCreator#29] opened 2018-12-18 21:57 UTC
After installing without any Errors, I run into the following Error when I run `create-corpora` on my local clips.tsv file (from the CV-alpha-1 dump, not the newest):

```
CorporaCreator$ create-corpora -d my-corpora -f ~/Downloads/CV/clips.tsv 
/home/josh/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1472: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)
Traceback (most recent call last):
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/ops.py", line 1012, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 205, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 65, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for +: 'float' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/create-corpora", line 11, in <module>
    load_entry_point('CorporaCreator==0.0.post0.dev72+gbdfaf64', 'console_scripts', 'create-corpora')()
  File "/usr/local/lib/python3.6/dist-packages/CorporaCreator-0.0.post0.dev72+gbdfaf64-py3.6.egg/corporacreator/tool.py", line 32, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/CorporaCreator-0.0.post0.dev72+gbdfaf64-py3.6.egg/corporacreator/tool.py", line 22, in main
    corpora.create()
  File "/usr/local/lib/python3.6/dist-packages/CorporaCreator-0.0.post0.dev72+gbdfaf64-py3.6.egg/corporacreator/corpora.py", line 63, in create
    corpus.create()
  File "/usr/local/lib/python3.6/dist-packages/CorporaCreator-0.0.post0.dev72+gbdfaf64-py3.6.egg/corporacreator/corpus.py", line 37, in create
    self._partition_corpus_data()
  File "/usr/local/lib/python3.6/dist-packages/CorporaCreator-0.0.post0.dev72+gbdfaf64-py3.6.egg/corporacreator/corpus.py", line 58, in _partition_corpus_data
    lambda df: (df.up_votes + df.down_votes) <= 1, :
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1466, in __getitem__
    for x in key)
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1466, in <genexpr>
    for x in key)
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/common.py", line 408, in _apply_if_callable
    return maybe_callable(obj, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/CorporaCreator-0.0.post0.dev72+gbdfaf64-py3.6.egg/corporacreator/corpus.py", line 58, in <lambda>
    lambda df: (df.up_votes + df.down_votes) <= 1, :
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/ops.py", line 1069, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/ops.py", line 1033, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/home/josh/.local/lib/python3.6/site-packages/pandas/core/ops.py", line 1018, in na_op
    result[mask] = op(x[mask], com._values_from_object(y[mask]))
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

**Comment by kdavis-mozilla** [comment] 2018-12-19 06:33
@Gregoor This is a dupe of issue #3 (Export a clean clips.tsv)

**Closed by kdavis-mozilla** 2018-12-19 06:33 UTC
